import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {Footer} from 'components/Footer'
import {Links} from 'components/Links'
import { Headline } from '@/components/Headline'
import { Header } from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className={styles.main}>
        <Headline
          title = "About Page"
          page = "about"
          number = {5}
          array = {[1, 2, 3]}
          obj = {{name:"hoge", age:21}}
          bool // trueの時はこの記述でOK(falseは省略できない)
          onClick = {() => alert("クリック")} // メソッドも渡せる
        >
          <code className={styles.code}>pages/about.js</code>
        </Headline>

        <Links />
      </main>
      <Footer/>
    </>
  )
}
