import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {Footer} from 'components/Footer'
import {Links} from 'components/Links'
import { Headline } from '@/components/Headline'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Headline title="Index Page" page="index">
          {/* ここに書いたものはchildrenとして渡る */}
          <code className={styles.code}>pages/index.js</code>
        </Headline>

        <Links />
      </main>
      <Footer/>
    </>
  )
}
